Repository EricHarrison72/gitGoblins, pull requests merged in 2024-03, with the labels that each got.

#71 Create database connection
  Code/__pycache__/app.cpython-312.pyc
  Code/__pycache__/db.cpython-312.pyc
  Code/app.py
  Code/flaskr/__init__.py
  Code/flaskr/__pycache__/__init__.cpython-312.pyc
  Code/flaskr/__pycache__/db.cpython-312.pyc
  Code/flaskr/__pycache__/init.cpython-312.pyc
  Code/flaskr/__pycache__/views.cpython-312.pyc
  Code/flaskr/db.py
  Code/flaskr/schema.sql
  Code/flaskr/templates/base.html
  Code/flaskr/templates/index.html
  Code/flaskr/templates/weather_summary.html
  Code/flaskr/views.py
  Code/instance/config.py
  Code/instance/database.db
Labels: Chore

#80 Move db population code to db.py
  Code/weatherApp/__init__.py
  Code/weatherApp/db.py
Labels: Refactor

#81 Added notes about flask databases
  Exploration Progress (for Rohit)/flask_databases.pdf
Labels: Documentation

#82 Sequence Diagrams
  Requirements/Sequence Diagrams/Sequence Diagram - Admin Notification.jpg
  Requirements/Sequence Diagrams/Sequence Diagram - Admin.jpg
  Requirements/Sequence Diagrams/Sequence Diagram - Login.jpg
  Requirements/Sequence Diagrams/Sequence Diagram - User.jpg
Labels: Documentation

#93 Links to login pages from home
  Code/weatherApp/__init__.py
  Code/weatherApp/templates/index.html
  Code/weatherApp/templates/login.html
  Code/weatherApp/templates/register.html
  Code/weatherApp/views.py
Labels: Feature

#95 Embed map
  Code/weatherApp/static/js/init_map.js
  Code/weatherApp/templates/map.html
  Code/weatherApp/views.py
Labels: Feature

#97 Database Persistence
  Code/pyproject.toml
  Code/tests/test_db.py
  Code/tests/test_views.py
  Code/tests/test_weatherApp.py
  Code/weatherApp/__init__.py
  Code/weatherApp/db.py
  Code/weatherApp/views.py
Labels: Refactor

#106 File Addition and UML Update
  Requirements/UML Diagrams/UML Class Diagram [WIP].jpg
  Requirements/UML Diagrams/UML Diagram [Final].jpg
Labels: Documentation

#107 Milestone 3
  Milestones/M1_Team_Info_&_Agreement.md
  Milestones/M2_Project_Description_&_Requirements.pdf
  Milestones/M3_Formal_Analysis_&_Architecture.pdf
Labels: Chore

#103 Registering an account
  Code/.DS_Store
  Code/requirements.txt
  Code/tests/conftest.py
  Code/tests/test_auth.py
  Code/tests/test_db.py
  Code/tests/test_views.py
  Code/weatherApp/__init__.py
  Code/weatherApp/auth.py
  Code/weatherApp/static/css/main.css
  Code/weatherApp/static/css/style.css
  Code/weatherApp/static/img/.DS_Store
  Code/weatherApp/static/img/ennui_cloud.png
  Code/weatherApp/static/img/happy_cloud.png
  Code/weatherApp/templates/auth/login.html.jinja
  Code/weatherApp/templates/auth/register.html.jinja
  Code/weatherApp/templates/base.html
  Code/weatherApp/templates/base.html.jinja
  Code/weatherApp/templates/index.html
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/templates/login.html
  Code/weatherApp/templates/map.html.jinja
  Code/weatherApp/templates/register.html
  Code/weatherApp/templates/select_date.html.jinja
  Code/weatherApp/templates/weather_summary.html
  Code/weatherApp/templates/weather_summary.html.jinja
  Code/weatherApp/views.py
Labels: Feature

#114 Coverage workflow
  .github/workflows/ci.yaml
  .github/workflows/cov.yaml
  Code/pyproject.toml
  Code/requirements.txt
Labels: Chore

#116 Coverage testing
  .github/workflows/ci.yaml
  .github/workflows/cov.yaml
  Code/.vscode/settings.json
  Code/pyproject.toml
  Code/requirements.txt
  Code/tests/testing_guide.md
Labels: Chore

#125 JS CI workflow
  .github/workflows/jsci.yaml
  Code/weatherApp/views.py
Labels: Chore

#121 Refactor Database Initialization
  Code/tests/conftest.py
  Code/tests/data.sql
  Code/tests/test_db.py
  Code/weatherApp/db.py
  Code/weatherApp/schema.sql
Labels: Refactor

#127 Refactor data query
  .github/workflows/ci.yaml
  Code/tests/test_queries.py
  Code/weatherApp/queries.py
  Code/weatherApp/templates/weather_summary.html.jinja
  Code/weatherApp/views.py
  Exploration Progress (for Rohit)/git_tips.md
Labels: Refactor

#128 Userid saved now
  Code/.DS_Store
  Code/tests/test_auth.py
  Code/weatherApp/auth.py
  Code/weatherApp/schema.sql
  Code/weatherApp/templates/auth/register.html.jinja
  Code/weatherApp/templates/base.html.jinja
  Code/weatherApp/views.py
Labels: bug

#139 Basic Graph Set-up
  Code/requirements.txt
  Code/tests/data.sql
  Code/tests/test_queries.py
  Code/weatherApp/graphs.py
  Code/weatherApp/queries.py
  Code/weatherApp/templates/graph.html.jinja
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/views.py
Labels: Feature

#147 Tests for views.py
  Code/tests/test_views.py
  Code/weatherApp/views.py
Labels: Chore

#154 Test markers
  Code/tests/initMap.test.js
  Code/weatherApp/static/js/init_map.js
Labels: Chore

#156 Major Front End Changes: template restructuring, macros, cosmetics
  .gitignore
  Code/tests/submit.test.js
  Code/tests/test_jinja_macros.py
  Code/tests/test_views.py
  Code/weatherApp/queries.py
  Code/weatherApp/static/css/style.css
  Code/weatherApp/static/js/location_select.js
  Code/weatherApp/static/js/submit.js
  Code/weatherApp/templates/base.html.jinja
  Code/weatherApp/templates/features/graph_current.html.jinja
  Code/weatherApp/templates/features/graph_past.html.jinja
  Code/weatherApp/templates/features/map.html.jinja
  Code/weatherApp/templates/features/weather_summary.html.jinja
  Code/weatherApp/templates/graph.html.jinja
  Code/weatherApp/templates/helpers/selectors.html.jinja
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/templates/location_select.html.jinja
  Code/weatherApp/templates/map.html.jinja
  Code/weatherApp/templates/select_date.html.jinja
  Code/weatherApp/templates/weather_summary.html.jinja
  Code/weatherApp/views.py
Labels: Refactor

#164 Weather predictions
  .gitignore
  Code/requirements.txt
  Code/tests/test_predictions.py
  Code/weatherApp/db.py
  Code/weatherApp/predictions.py
  Code/weatherApp/templates/features/weather_summary.html.jinja
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/views.py
Labels: Feature

#161 Connecting userId to cityId
  Code/.DS_Store
  Code/tests/test_auth.py
  Code/tests/test_views.py
  Code/weatherApp.sqlite
  Code/weatherApp/.DS_Store
  Code/weatherApp/__init__.py
  Code/weatherApp/admin.py
  Code/weatherApp/auth.py
  Code/weatherApp/schema.sql
  Code/weatherApp/static/.DS_Store
  Code/weatherApp/static/css/style.css
  Code/weatherApp/static/js/admin.js
  Code/weatherApp/templates/admin_dashboard.html.jinja
  Code/weatherApp/templates/auth/admin_register.html.jinja
  Code/weatherApp/templates/auth/login.html.jinja
  Code/weatherApp/templates/auth/passcode.html.jinja
  Code/weatherApp/templates/auth/register.html.jinja
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/views.py
Labels: Feature

#168 User city to admin branch
  Code/.DS_Store
  Code/tests/test_auth.py
  Code/tests/test_views.py
  Code/weatherApp/admin.py
  Code/weatherApp/auth.py
  Code/weatherApp/schema.sql
  Code/weatherApp/static/css/style.css
  Code/weatherApp/templates/admin_dashboard.html.jinja
  Code/weatherApp/templates/auth/admin_register.html.jinja
  Code/weatherApp/templates/auth/login.html.jinja
  Code/weatherApp/templates/auth/passcode.html.jinja
  Code/weatherApp/templates/auth/register.html.jinja
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/views.py
Labels: Chore

#179 scrum 12 added
  .DS_Store
  Scrum Meetings/SCRUM MEETING WEEK (12).pdf
Labels: Documentation

#167 Email framework
  Code/requirements.txt
  Code/tests/test_notification.py
  Code/weatherApp/__init__.py
  Code/weatherApp/notification.py
  Code/weatherApp/templates/notif/weather_alert.html.jinja
Labels: Chore

#183 Milestone 4 Report
  Milestones/M4_Testing_Update.pdf
Labels: Documentation

#184 Homepage
  Code/weatherApp/static/css/style.css
  Code/weatherApp/static/img/arrows/E.png
  Code/weatherApp/static/img/arrows/ENE.png
  Code/weatherApp/static/img/arrows/ESE.png
  Code/weatherApp/static/img/arrows/N.png
  Code/weatherApp/static/img/arrows/NE.png
  Code/weatherApp/static/img/arrows/NNE.png
  Code/weatherApp/static/img/arrows/NNW.png
  Code/weatherApp/static/img/arrows/NW.png
  Code/weatherApp/static/img/arrows/S.png
  Code/weatherApp/static/img/arrows/SE.png
  Code/weatherApp/static/img/arrows/SSE.png
  Code/weatherApp/static/img/arrows/SSW.png
  Code/weatherApp/static/img/arrows/SW.png
  Code/weatherApp/static/img/arrows/W.png
  Code/weatherApp/static/img/arrows/WNW.png
  Code/weatherApp/static/img/arrows/WSW.png
  Code/weatherApp/static/img/no_rain.png
  Code/weatherApp/static/img/rain.png
  Code/weatherApp/static/img/temp_high.png
  Code/weatherApp/static/img/temp_low.png
  Code/weatherApp/templates/features/weather_summary.html.jinja
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/views.py
Labels: Chore
