Repository EricHarrison72/gitGoblins, pull requests merged in 2024-04, with the labels that each got.

#165 Graph Update - class structure, wind & rain graphs, tests
  Code/pyproject.toml
  Code/tests/data.sql
  Code/tests/submit.test.js
  Code/tests/test_graphs.py
  Code/tests/test_jinja_macros.py
  Code/tests/test_queries.py
  Code/weatherApp/graphs.py
  Code/weatherApp/queries.py
  Code/weatherApp/static/js/submit.js
  Code/weatherApp/templates/features/graph_current.html.jinja
  Code/weatherApp/templates/features/graphs.html.jinja
  Code/weatherApp/templates/features/map.html.jinja
  Code/weatherApp/templates/features/weather_summary.html.jinja
  Code/weatherApp/templates/helpers/selectors.html.jinja
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/views.py
Labels: Feature, Chore

#190 Summary improvements
  Code/tests/test_auth.py
  Code/tests/test_jinja_macros.py
  Code/tests/test_queries.py
  Code/tests/test_views.py
  Code/tests/test_weather.py
  Code/weatherApp/graphs.py
  Code/weatherApp/queries.py
  Code/weatherApp/static/css/style.css
  Code/weatherApp/templates/base.html.jinja
  Code/weatherApp/templates/features/graphs.html.jinja
  Code/weatherApp/templates/features/map.html.jinja
  Code/weatherApp/templates/features/weather_summary.html.jinja
  Code/weatherApp/templates/helpers/data_display.html.jinja
  Code/weatherApp/templates/helpers/icon_display.html.jinja
  Code/weatherApp/templates/helpers/selectors.html.jinja
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/views.py
  Code/weatherApp/weather.py
Labels: Chore

#195 Fix view and auth tests
  Code/tests/auth_actions.py
  Code/tests/conftest.py
  Code/tests/data.sql
  Code/tests/test_admin.py
  Code/tests/test_auth.py
  Code/tests/test_predictions.py
  Code/tests/test_queries.py
  Code/tests/test_views.py
  Code/weatherApp/admin.py
  Code/weatherApp/graphs.py
  Code/weatherApp/views.py
Labels: Refactor

#203 Link pages
  Code/weatherApp/auth.py
  Code/weatherApp/static/css/style.css
  Code/weatherApp/templates/admin_dashboard.html.jinja
  Code/weatherApp/templates/base.html.jinja
  Code/weatherApp/templates/features/map.html.jinja
  Code/weatherApp/templates/helpers/navbar_display.html.jinja
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/templates/settings.html.jinja
  Code/weatherApp/views.py
Labels: Chore

#191 Notification System
  Code/tests/auth_actions.py
  Code/tests/data.sql
  Code/tests/test_admin.py
  Code/tests/test_notification.py
  Code/tests/test_queries.py
  Code/weatherApp/__init__.py
  Code/weatherApp/admin.py
  Code/weatherApp/auth.py
  Code/weatherApp/notification.py
  Code/weatherApp/queries.py
  Code/weatherApp/templates/admin_dashboard.html.jinja
  Code/weatherApp/templates/helpers/selectors.html.jinja
  Code/weatherApp/templates/notif/email_high_temp.html.jinja
  Code/weatherApp/templates/notif/email_high_winds.html.jinja
  Code/weatherApp/templates/notif/email_low_temp.html.jinja
  Code/weatherApp/templates/notif/email_rain.html.jinja
  Code/weatherApp/templates/notif/weather_alert.html.jinja
Labels: Feature

#206 Rename weather module
  Code/tests/test_icons.py
  Code/weatherApp/icons.py
  Code/weatherApp/views.py
Labels: Chore

#194 Darkmode
  Code/tests/test_settings.py
  Code/tests/test_views.py
  Code/weatherApp/.DS_Store
  Code/weatherApp/__init__.py
  Code/weatherApp/graphs.py
  Code/weatherApp/settings.py
  Code/weatherApp/static/.DS_Store
  Code/weatherApp/static/css/style.css
  Code/weatherApp/static/img/.DS_Store
  Code/weatherApp/static/img/arrows/.DS_Store
  Code/weatherApp/static/img/arrows/ENE.png
  Code/weatherApp/static/img/arrows/ESE.png
  Code/weatherApp/static/img/arrows/NE.png
  Code/weatherApp/static/img/arrows/NNE.png
  Code/weatherApp/static/img/arrows/NNW.png
  Code/weatherApp/static/img/arrows/NW.png
  Code/weatherApp/static/img/arrows/SE.png
  Code/weatherApp/static/img/arrows/SSE.png
  Code/weatherApp/static/img/arrows/SSW.png
  Code/weatherApp/static/img/arrows/SW.png
  Code/weatherApp/static/img/arrows/WNW.png
  Code/weatherApp/static/img/arrows/WSW.png
  Code/weatherApp/static/js/darkmode.js
  Code/weatherApp/templates/admin_dashboard.html.jinja
  Code/weatherApp/templates/auth/admin_register.html.jinja
  Code/weatherApp/templates/auth/login.html.jinja
  Code/weatherApp/templates/auth/passcode.html.jinja
  Code/weatherApp/templates/auth/register.html.jinja
  Code/weatherApp/templates/base.html.jinja
  Code/weatherApp/templates/features/graphs.html.jinja
  Code/weatherApp/templates/features/map.html.jinja
  Code/weatherApp/templates/features/weather_summary.html.jinja
  Code/weatherApp/templates/helpers/navbar_display.html.jinja
  Code/weatherApp/templates/helpers/selectors.html.jinja
  Code/weatherApp/templates/index.html.jinja
  Code/weatherApp/templates/settings.html.jinja
  Code/weatherApp/views.py
Labels: Feature

#210 Cleanup
  Code/requirements.txt
  Code/tests/data.sql
  Code/tests/initMap.test.js
  Code/tests/submit.test.js
  Code/tests/test_admin.py
  Code/tests/test_auth.py
  Code/tests/test_db.py
  Code/tests/test_icons.py
  Code/tests/test_jinja_macros.py
  Code/tests/test_queries.py
  Code/weatherApp/admin.py
  Code/weatherApp/schema.sql
  Code/weatherApp/settings.py
  Code/weatherApp/templates/admin_dashboard.html.jinja
  Code/weatherApp/templates/auth/admin_register.html.jinja
  Code/weatherApp/templates/auth/login.html.jinja
  Code/weatherApp/templates/auth/passcode.html.jinja
  Code/weatherApp/templates/auth/register.html.jinja
  Code/weatherApp/templates/base.html.jinja
  Code/weatherApp/templates/features/graphs.html.jinja
  Code/weatherApp/templates/features/map.html.jinja
  Code/weatherApp/templates/features/weather_summary.html.jinja
  Code/weatherApp/templates/settings.html.jinja
  Database Design/Database DDL.txt
  Database Design/Database Design.PNG
  Exploration and Research/.DS_Store
  Exploration and Research/CommandUML.png
  Exploration and Research/Development_Resources_[WIP].pdf
  Exploration and Research/ObserverUML.png
  Exploration and Research/Similar weather websites.pdf
  Exploration and Research/design_patterns.pdf
  Exploration and Research/flask_databases.pdf
  Exploration and Research/git_tips.md
  Exploration and Research/testing_exploration.md
Labels: Chore

#213 Handover docs
  Database_Design/Database DDL.txt
  Database_Design/Database Design.PNG
  Exploration_and_Research/.DS_Store
  Exploration_and_Research/CommandUML.png
  Exploration_and_Research/Development_Resources_[WIP].pdf
  Exploration_and_Research/ObserverUML.png
  Exploration_and_Research/Similar weather websites.pdf
  Exploration_and_Research/design_patterns.pdf
  Exploration_and_Research/flask_databases.pdf
  Exploration_and_Research/git_tips.md
  Exploration_and_Research/testing_exploration.md
  Scrum_Meetings/.DS_Store
  Scrum_Meetings/SCRUM MEETING WEEK (10).pdf
  Scrum_Meetings/SCRUM MEETING WEEK (11).pdf
  Scrum_Meetings/SCRUM MEETING WEEK (12).pdf
  Scrum_Meetings/SCRUM MEETING WEEK (13).pdf
  Scrum_Meetings/SCRUM MEETING WEEK (14) (1).pdf
  Scrum_Meetings/SCRUM MEETING WEEK (5).pdf
  Scrum_Meetings/SCRUM MEETING WEEK (6).pdf
  Scrum_Meetings/SCRUM MEETING WEEK (8).pdf
  Scrum_Meetings/SCRUM MEETING WEEK (9).pdf
  Scrum_Meetings/SCRUM-MEETING-Template.docx
  Scrum_Meetings/Scrum Meeting Week 4.pdf
  installation_guide.md
Labels: Documentation

#214 Add M5
  Milestones/M5_Final_Report_&_Delivery.pdf
Labels: Documentation
